# Generated by Django 3.0.5 on 2020-05-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200516_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hasSubscribed',
        ),
    ]
